before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - main: ./cmd/terraform-provider-kops
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
      - linux
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
